### ISSUE TITLE
Garage Door HTTP Methode

### ISSUE THREAD

**Issue by ZnarfMe** [rudders/homebridge-http#14]
I would like to extend the device types of this module. The eve app on ios already detecting the http device as a lock.

    } else if (this.service == "GarageDoorOpener") {
      var garageDoorOpenerService = new Service.GarageDoorOpener(this.name);
      garageDoorOpenerService
      .on('set', this.setDoorState.bind(this));
      return [informationService, garageDoorOpenerService];
    }

Just with the already existing function setPowerState I cannot lock and unlock the door.

It would be great that somebody is helping me to make the plugin even better.

**Comment by NovaGL** [comment]
I already have done a door method, I had a pull request but it didn't go through.

Have a look here, I have done it as a lock mechanism. Garage requires more than one characteristic so I doubt that would work. 

Look here https://github.com/NovaGL/homebridge-httpstatus

**Comment by NovaGL** [comment]
Closing this issue, answer has been given and no response.
