### ISSUE TITLE
Client connection error: read ETIMEDOUT 

### ISSUE THREAD

**Issue by nizaga** [rudders/homebridge-http#19]
Hi,
My homebridge is working fine but I check the log files and i see a ETIMEDOUT every 2-3 hours.

Running homebridge on RPI, node v.5.2.0...

Any idea?

Thanks!

Sat, 30 Jan 2016 02:02:09 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 30 Jan 2016 07:02:52 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 30 Jan 2016 10:22:15 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Sat, 30 Jan 2016 17:32:12 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 30 Jan 2016 19:12:03 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
      throw er; // Unhandled 'error' event
Sun, 31 Jan 2016 03:54:10 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 04:54:21 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 06:04:10 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 06:24:10 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 06:54:10 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 08:04:11 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sun, 31 Jan 2016 10:49:30 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ECONNRESET
Sun, 31 Jan 2016 11:15:48 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ECONNRESET
Sun, 31 Jan 2016 23:46:01 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 00:24:11 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 01:05:41 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 02:25:50 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 03:25:39 GMT EventedHTTPServer [fe80::4a2:605a:b8fe:3a50] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 04:14:12 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 05:45:40 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Mon, 01 Feb 2016 08:25:31 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Tue, 02 Feb 2016 01:46:01 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Tue, 02 Feb 2016 02:34:12 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Tue, 02 Feb 2016 06:34:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Tue, 02 Feb 2016 07:24:12 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Tue, 02 Feb 2016 08:14:05 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Tue, 02 Feb 2016 19:54:35 GMT EventedHTTPServer [fe80::4a2:605a:b8fe:3a50] Client connection error: read ETIMEDOUT
Tue, 02 Feb 2016 22:34:13 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Wed, 03 Feb 2016 01:14:13 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Wed, 03 Feb 2016 03:04:13 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Wed, 03 Feb 2016 04:04:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Wed, 03 Feb 2016 05:44:13 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Wed, 03 Feb 2016 07:44:04 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Wed, 03 Feb 2016 19:04:03 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Thu, 04 Feb 2016 00:25:40 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 01:52:32 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 02:52:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 07:06:06 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT

**Comment by rudders** [comment]
This is a common http error that suggests the device you are communicating with is falling of the network for some reason. This could be anything from a flakey wifi connection to the device, multiple networks path from your Homebridge host (wifi + eth) or a VPN kicking in on your Homebridge host that is making the rest of your network unreachable.

Take a look at your network config and provide details of it to this issue if this isn't enough of a clue to get you up and running.

**Comment by nizaga** [comment]
hi, very simple etc/network/interfaces:

no WIFI adator, ethernet cable, IP fixed by MAC in the router.

----------------------------------
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback
allow-hotplug wlan0
auto wlan0
----------------------------------

any help? 

Thanks again,

Nacho

**Comment by nizaga** [comment]
oh... could the problem be related to having enabled the following (even with no wifi adapter)?? i will try out tonight... 

allow-hotplug wlan0
auto wlan0

**Comment by nizaga** [comment]
hi, i have commented the following lines from my interfaces:

# allow-hotplug wlan0
# auto wlan0

and my interfaces includes only:

source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

and still getting the following: (f:192.168.1.128 is my iphone)

Thu, 04 Feb 2016 02:52:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 07:06:06 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 08:12:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 09:45:31 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Thu, 04 Feb 2016 23:02:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Thu, 04 Feb 2016 23:32:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Fri, 05 Feb 2016 01:22:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Fri, 05 Feb 2016 03:22:22 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Fri, 05 Feb 2016 04:23:12 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Fri, 05 Feb 2016 08:52:14 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read EHOSTUNREACH
Fri, 05 Feb 2016 23:42:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 00:12:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 00:45:40 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 01:15:40 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 03:32:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 04:42:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 05:22:33 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 06:52:23 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT

any advice???

**Comment by nizaga** [comment]
further information and further questions:

my homebridge is on port 51826, i am getting the errors at night, when i am not using EVE.

why the http server changes the listening port?

HTTP server listening on port 54827
HTTP server listening on port 54826

Eve is working fine, but i would like to know why i am getting the ETIMEOUT error,,,


Sat, 06 Feb 2016 05:16:46 GMT EventedHTTPServer [::ffff:192.168.1.128] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Sat, 06 Feb 2016 05:18:37 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
Sat, 06 Feb 2016 05:18:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 54827
Sat, 06 Feb 2016 05:18:37 GMT EventedHTTPServer [::ffff:127.0.0.1] Client connection closed
Sat, 06 Feb 2016 05:18:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed
Sat, 06 Feb 2016 05:18:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed
Sat, 06 Feb 2016 05:20:02 GMT ZWayServer Got 1 updates.
Sat, 06 Feb 2016 05:20:06 GMT ZWayServer Got 2 updates.
Sat, 06 Feb 2016 05:20:37 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
Sat, 06 Feb 2016 05:20:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 54827
Sat, 06 Feb 2016 05:20:37 GMT EventedHTTPServer [::ffff:127.0.0.1] Client connection closed
Sat, 06 Feb 2016 05:20:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed
Sat, 06 Feb 2016 05:20:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed
Sat, 06 Feb 2016 05:22:33 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection error: read ETIMEDOUT
Sat, 06 Feb 2016 05:22:33 GMT EventedHTTPServer [::ffff:192.168.1.128] Client connection closed
Sat, 06 Feb 2016 05:22:33 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP connection was closed
Sat, 06 Feb 2016 05:22:33 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP server was closed
Sat, 06 Feb 2016 05:22:37 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
Sat, 06 Feb 2016 05:22:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 54826
Sat, 06 Feb 2016 05:22:37 GMT EventedHTTPServer [::ffff:127.0.0.1] Client connection closed
Sat, 06 Feb 2016 05:22:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed
Sat, 06 Feb 2016 05:22:37 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed
Sat, 06 Feb 2016 05:23:07 GMT ZWayServer Got 8 updates.

thanks again!

**Comment by nizaga** [comment]
sorry for keeing asking....

If i run  netstat -tulpn i get homebridge listening on two ports: 51826 and 54826...

why 54826  if i configured homebridge in the config.json to run on  51826? I am lost......

Thanks!   

pi@raspberrypi:~ $ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3400            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:2812          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::6144                 :::*                    LISTEN      -
tcp6       0      0 :::54826                :::*                    LISTEN      8510/homebridge
tcp6       0      0 :::8080                 :::*                    LISTEN      -
tcp6       0      0 :::51826                :::*                    LISTEN      8510/homebridge
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::3001                 :::*                    LISTEN      -

**Comment by NovaGL** [comment]
These aren't problems related to homebridge-http you might get better answers at the homebridge repo page.

**Comment by nizaga** [comment]
you are right, sorry...

thanks

**Comment by NovaGL** [comment]
Closing this as it is not related to Homebridge-Http, if you have a specific bug related to this plugin feel free to reopen it.
