### ISSUE TITLE
Simple Http request

### ISSUE THREAD

**Issue by NiackBuster** [rudders/homebridge-http#2]
Hello ! Is there a way to modify the package.json or else to make a simple http request instead of https ?
I tryed to change https to http in the config.json in the accessories part but this not solve the pb.
I tryed to write directly type  : http://login:pass@adress?value=....  idem...  (this request works in a browser)

+

**Comment by rudders** [comment]
http requests should work fine.
Add the username and password into the configuration rather than encoding them in the url.
also try setting sendImmediately to true .

**Comment by NiackBuster** [comment]
yes :)


       _header: 'GET /api/sceneControl?id=19&action=start HTTP/1.1\r\nhost: 192.168.0.201\r\nauthorization: Basic YWRtaW46YWJuREVGT1cx\r\ncontent-length: 14\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/api/sceneControl?id=19&action=start',
        parser: null,
        res: [Circular] },
     ntick: true,
     response: [Circular],
     originalHost: '192.168.0.201',
     originalHostHeaderName: 'host',
     responseContent: [Circular],
     _destdata: true,
     _ended: true,
     _callbackCalled: true },
  toJSON: [Function: responseToJSON],
  caseless: 
   Caseless {
     dict: 
      { 'content-type': 'text/html',
        'content-length': '349',
        connection: 'close',
        date: 'Wed, 18 Nov 2015 21:55:39 GMT',
        server: 'lighttpd/1.4.35' } },
  read: [Function],
  body: '<?xml version="1.0" encoding="iso-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n <head>\n  <title>400 - Bad Request</title>\n </head>\n <body>\n  <h1>400 - Bad Request</h1>\n </body>\n</html>\n' }
[machine à café] <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>400 - Bad Request</title>
 </head>
 <body>
  <h1>400 - Bad Request</h1>
 </body>
</html>

**Comment by rudders** [comment]
Here is my config details that work fine for a similar service. Am about to get one plane. Will try and look in more detail later in the day. Can you post your config please.

       {
            "accessory": "Http",
            "name": "SecuritySpy",
            "on_url": "http://192.168.0.77:8090/++ssControlActiveMode?cameraNum=0",
            "on_body": "",
            "off_url": "http://192.168.0.77:8090/++ssControlPassiveMode?cameraNum=0",
            "off_body": "",
            "brightness_url": "http://192.168.1.22:3030/devices/23222/brightness/%b",
            "username": "xxx",
            "password": "yay",
             "sendimmediately": true,
            "http_method": "GET",
             "service": "Switch",
              "brightnessHandling": "no"
        }

**Comment by NiackBuster** [comment]
Whaaaa ! That works :)
I deleted what was in brakets :  
 "on_body": "",
"off_body": "",
I wrote : true instead of True

:) Thanks so much !!

**Comment by rudders** [comment]
Glad it's sorted.
