### ISSUE TITLE
Additional Accessories?

### ISSUE THREAD

**Issue by tannebil** [rudders/homebridge-http#20]
Any plan to add additional accessories? Being able to display the state of a window/door sensor would be great. Right now, I just hack them in as lights with a dummy device for on/off. Works but looks ugly.

Also, can homebridge plug-ins trigger events in HomeKit? For example, I'd like the garage and entryway lights to come on when the garage door opens.  I can trigger an http command when the door opens but where do I send it?

**Comment by NovaGL** [comment]
Hi,

This is a simple plugin which will not have additional accessories, it is meant to be a base plugin.

If you would like additional accessories do a pull release on this plugin - https://github.com/NovaGL/homebridge-http-advanced

And I will add them in, I already have a door accessory setup but I can't monitor open\close state so I haven't updated it. I have motion sensors set up so maybe you could use that?

Triggers are done by the app on your phone not Homebridge, use an app such as Eve and you will see you can do, If door opens turn light on.

**Comment by olehs** [comment]
Why do we need hard-coded accessories? Check latest commit in fork I made. It's all in config - any accessories, any characteristics.

**Comment by tannebil** [comment]
Interesting. I'll give it a try. My immediate reaction is that I'm going to end up with a busy and hard to debug config.json (which is still far, far better than having to update index.js. 

I've got about 20 dry contacts and 10 lights controlled via http so that's a lot of entries that are 90% boilerplate but are full of braces that have to match. Is there some way to simplify it when there are multiple occurrences of an accessory? My JS/JSON knowledge would fit on the head of a pin so the answer may be obvious to you.

Also, when something about an accessory/service in homebridge isn't quite the way you want or is missing, is there an override other than forking homebridge?

I cloned the homebridge-http-advanced repo and am busy hacking it up to learn enough Linux/JavaScript/JSON/Git/GitHub/NPM/homebridge/homebridge-http-advanced/HomeKit to be dangerous.

**Comment by rudders** [comment]
@olehs awesome plugin! I'd agree with @tannebil through it's not for the feint hearted. 

I'd love to see you rename this and publish it as a new plugin in it's own right with updated README etc - perhaps homebridge-configurable-http or perhaps something a bit more catchy. there has been discussion about adding this kind of stuff to homebridge-http but it was agreed that this should remain a relatively simple plugin that is easy to understand and fork. Yours, like advanced, should be their own plugin IMHO.

**Comment by olehs** [comment]
Yes, you're right - config looks really scary with all those braces. But in my installation, config file will be generated automatically by my smart-home server, because all settings are stored there and all HTTP requests are processed by that server.

I guess to make it more user-friendly, each accessory has to be extracted to a separate file and included in main file or loaded from a special directory.

Besides, my http-requests are very similar, so I could even apply some template processing to URL's, but not sure this would be useful for others.

**Comment by rudders** [comment]
There is no doubt that flexibility breeds complexity but that could be explained in the readme. I really think it's work publishing it in it's own right - you'll get lots of feedback from the community i'm sure ;)

**Comment by rudders** [comment]
@tannebil is this resolved to your satisfaction? May I close the issue?

**Comment by tannebil** [comment]
Sure. Is there a way to ask questions and have conversations without creating a GitHub  issue? Should I be using The homebridge Slack instance?

**Comment by rudders** [comment]
The slack community is pretty lively and there are lots of channels that get specific to plugins and issues. Github issues are fine but frequently go way off topic so I like to close them out to keep it a bit tidy.
