### ISSUE TITLE
Can status url be called on the fly?

### ISSUE THREAD

**Issue by adamoc** [rudders/homebridge-http#24]
When I ask Siri what the status is of my device, nothing is called via Homebridge. Is this intentional? Or is Polling the only way.

I have a few issues with Polling. I had to change it from 300 to 15000 because it was hanging my socket server. It was also causing X10 to send an on command when the status was off. If I restarted Homebridge, it would then turn everything on in the house. Not good when I was testing at night. 

All I want is for my status url to be called when I ask Siri, "is my office light on?". Is that possible?

**Comment by adamoc** [comment]
I've found what I'm after using readablehttp.

**Comment by NovaGL** [comment]
You can't use realtime polling them, everything in readablehttp is in this repo with many fixes
