### ISSUE TITLE
Would like to add support for thermostat settings. Can anyone advise?

### ISSUE THREAD

**Issue by psmith3** [rudders/homebridge-http#26]
I have this working on an http thermostat (Proliphix) and have it responding like a light. I can set the temp using the brightness value by saying "turn on thermostat to 70%", but would like to get it working like a thermostat. Can anyone point me in the right direction to do this? I cannot find much on what all the commands should look like as a thermostat accessory.

**Comment by NovaGL** [comment]
You are going to get better support if you ask in the homebridge repo not this one but here is what you are missing

```xml
  // Required Characteristics
  this.addCharacteristic(Characteristic.CurrentHeatingCoolingState);
  this.addCharacteristic(Characteristic.TargetHeatingCoolingState);
  this.addCharacteristic(Characteristic.CurrentTemperature);
  this.addCharacteristic(Characteristic.TargetTemperature);
  this.addCharacteristic(Characteristic.TemperatureDisplayUnits);
```
