### ISSUE TITLE
use homebridge-http to read http device temperature?

### ISSUE THREAD

**Issue by JangoBritt** [rudders/homebridge-http#29]
So i have a DLink Baby Monitor which has a temperature display.

I can read the Device state page on http://192.168.1.4/eng/web_event.cgi and it returns:

> motion_detected_1=off
> mdv1=0
> pir=off
> gp_input_0=off
> gp_input_1=off
> gp_input_2=off
> gp_input_3=off
> storage_full_sd=off
> storage_failure_sd=off
> in_recording=off
> audio_detected=off
> gp_output_0=off
> gp_output_1=off
> gp_output_2=off
> gp_output_3=off
> pan_pos=0.000000
> tilt_pos=0.000000
> zoom_mag=0.000000
> focus_step=0
> irled=on
> playing_music=off
> music_repeated=off
> night_led=off
> camera_name=Thomas
> speaker_occupied=off
> mic_muted=off
> td=normal
> 
> tdC=23
> tdF=73

Is there a way I could use the data from tdC= to return a temperature, and format is as a thermostat using this plugin?

**Comment by NovaGL** [comment]
This plugin won't do it but I can see you made another thread on the base homebridge plugin on how you would go about it.

Basically you need to add the characteristic for temperature, just look at other plugins that do thermos, then you just need to pull in the value that you got from the CURL.

**Comment by JangoBritt** [comment]
Thanks NovaGL. I don't know how to code that, so I'll have to just hope someone in the base homebridge thread knows an easy way to do it.

Looking at the HAP-NodeJS HomeKitTypes.js, there are a couple of service types that could be invoked from the above: CurrentTemperature, MotionDetected, AudioFeedback

**Comment by NovaGL** [comment]
I would use Characteristic.CurrentTemperature

You can add it to any service by doing this

.addCharacteristic(new Characteristic.CurrentTemperature())

Just make sure the current temp is easily accessible
