### ISSUE TITLE
using http plugin to manage occupancy

### ISSUE THREAD

**Issue by JangoBritt** [rudders/homebridge-http#34]
So I have an idea. I don't know exactly how to run with it, but thought this might be a good starting point.

Currently, homekit doesn't support multiple occupancy for Location triggers.

I can use a Location Trigger to set off a scene when I leave the house
My wife can do the same
but we can't use a location trigger to only set off when both of us have left.

The way this can be done is to use a Location Trigger on each iPhone to change the state or variable of something, and then use that value to manage the multi occupancy.

There could be 2 ways of doing this, but HomeKit would need to be able to read the state of either.
1. One Pseudo Device per household

> When Adam Leaves, decrease brightness\temperature value -1
> When Mrs. Leaves, decrease brightness\temperature value -1
> When Adam Arrives, increase brightness\temperature value +1
> When Mrs. Arrives, increase brightness\temperature value +1
> 
> When brightness\temperature = 0, switch on roomba
> when brightness\temperature >0, switch off (dock) roomba
1. One Pseudo Device per occupant

> When Adam Leaves the house, set AdamHome to OFF
> When Mrs. Leaves the house, set MrsHome to OFF
> When Adam Arrives Home, set AdamHome to ON
> When MRs. Arrives Home, Set MrsHome to ON
> 
> When AdamHome = OFF and MrsHome = OFF , switch on Roomba!
> When AdamHome = ON, Switch Off (Dock) Roomba
> When MrsHome = ON, Switch Off (Dock) Roomba

I suspect that number 2 will be more likely, as not sure how homekit triggers work with increasing\decreasing, rather than just running a pre-set scene.

The question is, how to implement the pseudo device on HomeBridge, and allow it's state to be read for Value triggers.

**Comment by cybertza** [comment]
https://www.npmjs.com/package/homebridge-people may be a step in the right direction @JangoBritt
