### ISSUE TITLE
Documentation: services

### ISSUE THREAD

**Issue by TonyFeestneus** [rudders/homebridge-http#39]
What are the services that can be enabled by this? I can only get Light and Switch to work, but an overview of what is possible would be greatly appreciated!
Thanks.

**Comment by NovaGL** [comment]
That's all. It's meant to be a base basic plugin which people can build upon. It is kept light on purpose

**Comment by TonyFeestneus** [comment]
Clear. Thanks for the quick response. Other plugins you can recommend to build upon this one?

**Comment by TonyFeestneus** [comment]
Any tips on publishing multiple 'rooms', since now they're all added to the same room

**Comment by cybertza** [comment]
@TonyFeestneus that is handled in the application side of things and is much clearer in IOS10

you just head into the detials of the device and then you can specify a room, or hide it by disregarding the show on fav's slider.
