### ISSUE TITLE
"service" : "Door"?

### ISSUE THREAD

**Issue by dolanmiu** [rudders/homebridge-http#47]
At the moment, I have `"service": "Light"`, but I really want the ability to create a door.

Right now, I have to say to Siri:

"**Turn on** the Chicken Door", as opposed to:

"**Close** the Chicken Door"

**Comment by NovaGL** [comment]
You can add your own services eg Door but this plugin won't add more services

**Comment by dolanmiu** [comment]
It looks like `Switch` and `Light` are hard-coded into the plugin:

https://github.com/rudders/homebridge-http/blob/master/index.js#L60-L71

It would be nice if it can be configurable, but that may be too much to ask for

**Comment by NovaGL** [comment]
It can't be customised as every service has different characteristics. I have one called http-advanced which has more services. Go wild on that and add as many services as you want
