### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by fullphat** [rudders/homebridge-http#48]
We'd like to use this to integrate Snarl into HomeKit.  It's already working well, but could we ask if it's possible to actually proxy the accessory settings to a remote URL as well?

At the moment, the user needs to edit config.json to include each accessory and the type it is - it'd be ideal if those settings could be gathered from a URL instead.  This might be more an issue for HomeBridge itself but we thought we'd raise it here first.

**Comment by NovaGL** [comment]
Plugins don't control the config file. Best to ask in Homebridge repo
