### ISSUE TITLE
Shutters not supported

### ISSUE THREAD

**Issue by mymazl** [rudders/homebridge-http#52]
If I use a shutter in my configuration like this, i will get an exception and homebridge will terminate:

	   {
	        "accessory": 			"Http",
			"name": 				"Jalousie Office",
			"switchHandling": 		"realtime",
			"http_method": 			"GET",
			"on_url":      			"http://xxx",
			"off_url":     			"http://yyy",
			"status_url":  			"http://zzz",				
			"service": 				"Shutter",
			"brightnessHandling": 	"no",
			"brightness_url":     	"",
			"brightnesslvl_url":  	""											    
       }

Does anybody uses homebridge-http for something else then lights?
Are there any samples?

Thanks!

**Comment by NovaGL** [comment]
Since this is only a basic plugin not meant to service every purpose the only services available are Switch and Light.

Feel free to build your own plugin based on this.

Since you only have the option of switch and light using any other wording will cause Homebridge to fail.
