### ISSUE TITLE
Use this plugin for shutters

### ISSUE THREAD

**Issue by TRIROG** [rudders/homebridge-http#6]
Since all the shutters in my home are controlled via URL (i open certain url for up and another for down command) so  i decided to use the homebridge-http plugin.

I managed to get it working, however siri only responds to shutters ON and shutters OFF (since the plugin is written for power outlet (ON and OFF command)).

How would it be possible to change this for Up and DOWN?

**Comment by rudders** [comment]
Set up a Scene in HomeKit and just ask Siri to activate the scene. Easiest way around this and works pretty well.

**Comment by TRIROG** [comment]
Thanks!
How would i go about opening my garage door (also controlled by visiting single URL)?
Use same URL for on and off?

**Comment by rudders** [comment]
So it's a toggle URL?
Just use same URLs for both I'd guess.

**Comment by TRIROG** [comment]
Thanks!
I was just for a way to "clean up the thing" and i thought i could just "rename commands" and add them to another class, so my shutters wouldn't show up ad power outlets ...

**Comment by rudders** [comment]
It's deep in the bowels of accessories and characteristics - can probably be done if you want to dig into it and rewrite the module...
