### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by autumnwalker** [rudders/homebridge-http#7]
Getting an error when trying to connect to web server with self-signed certificate

`HTTP power function failed: self signed certificate`

Any way around this?

**Comment by rudders** [comment]
You're using and https url I assume - can you use an http url?

**Comment by autumnwalker** [comment]
Correct, using https url. When I switch to http I get `HTTP power function failed: read ECONNRESET`.

**Comment by rudders** [comment]
have you tried a POST rather than a GET (or visa versa)

**Comment by autumnwalker** [comment]
Yes, no change using either POST / GET.

**Comment by rudders** [comment]
can you post your config.json please - if you are using a userid and password for instance you might like to try sendImmediately

**Comment by autumnwalker** [comment]
```
    "accessories": [
        {
            "accessory": "Http",
            "name": "House Alarm",
            "on_url": "https://homebridge:8111/api/alarm/arm",
            "on_body": "",
            "off_url": "https://homebridge:8111/api/alarm/disarm",
            "off_body": "",
            "brightness_url": "",
            "username": "",
            "password": "",
            "sendimmediately": "",
            "http_method": "POST",
            "http_brightness_method": "POST",
            "service": "Switch",
            "brightnessHandling": "no"
        }
    ]
}
```

**Comment by rudders** [comment]
What happens when you try these url's in a Browser? or with curl from the command line, do they work okay?

**Comment by rudders** [comment]
you could try adding `rejectUnauthorized: false,` in the http call on line 36 of the index.js if you'd like.

`httpRequest: function(url, body, method, username, password, sendimmediately, callback) {
		request({
				url: url,
				body: body,
				method: method,
                                rejectUnauthorized: false,
				auth: {
					user: username,
					pass: password,
					sendImmediately: sendimmediately
				}
			},
			function(error, response, body) {
				callback(error, response, body)
			})'

**Comment by autumnwalker** [comment]
Both work immediately when I try in a browser.

Where can I find index.js?

**Comment by rudders** [comment]
So we know the problem then. code fix should work.
if you installed with npm -g then it's probably in here. 
/usr/lib/node_modules/homebridge-http

`npm -g root` will tell you to where your node modules are stored

**Comment by autumnwalker** [comment]
That did it. Thank you very much!

Is it possible to add something to config / code to toggle `rejectUnauthorized: false,` as an option?

**Comment by rudders** [comment]
I think it just be left false all the time - not really a big issue for this sort of work - I'll make some code changes and republish the module so you can just `npm -g update` to get the new module.

**Comment by autumnwalker** [comment]
Awesome, thanks!

**Comment by rudders** [comment]
module updated, tested and published. v0.0.4
