### ISSUE TITLE
Ability to set poll interval

### ISSUE THREAD

**Issue by moog-man** [rudders/homebridge-http#76]
I think 300ms for polling is putting a lot of strain onto the network and the target device. I propose to either have a property which allows to set the poll interval, or alternatively allow switchHandling to have a time instead of "realtime". The old behavior could be maintained when "realtime" is entered. Any other value from "300" - "60000" would then set the respective poll frequency.

**Comment by NovaGL** [comment]
Not sure if this still works as I haven't used this in awhile. But the polling time should be coming from "polling-to-event" can you try changing it in that module and see if it makes a difference

**Comment by moog-man** [comment]
I will try!

Matthias Schorer
Akilindastrasse 2a
82166 Gräfelfing

m: +49 170 542 4819
e: mschorer@me.com

sent from my iPhone 7

**Comment by marcetcheverry** [comment]
Agreed, polling at 300 milliseconds is way too intensive

**Comment by tamasharasztosi** [comment]
Have someone managed to set polling time higher?

**Comment by tamasharasztosi** [comment]
In your node_modules folder (/usr/lib/node_modules/homebridge-http/index.js) change interval time at the line 59.
}, { longpolling: true, interval: 300, longpollEventName: "statuspoll" });

300 (ms) -» 5000 (ms) worked for me
