### ISSUE TITLE
Possibility of changing service type?

### ISSUE THREAD

**Issue by Tommrodrigues** [rudders/homebridge-http#77]
Hey there, 
I've recently installed this plugin as a way of bridging HomeBridge and IFTTT to control an electric door and it's working great. However, there is a slight aesthetic issue that the icon in HomeKit is stuck as a switch and I can't find a way to change it either in the app, or in the config.json file. I have already changed the service in config.json to "Switch" from "Light" and have tried to change it to other things such as garage door opener, door and button but all have resulted in HomeBridge not starting properly. It would be great if you could let me know if there is a way of changing the service type so it will appear as a door or a garage door etc. (In my case the input for on and off is the same, so a button would do fine as well!). Don't worry if there isn't a way to do this as other than that it is all working well just the fact that is appears as a switch is slightly annoying. I really appreciate you making this plugin as it has made a real difference to my home.
Thank you in advance,
Tom

**Comment by NovaGL** [comment]
This was initially designed to just show you what you can do. It doesn't support things beyond light and switch.

You can try my repo but I still don't do garage doors and there is no plans to add more features.
https://github.com/NovaGL/homebridge-http-advanced
