### ISSUE TITLE
Additional accesory types

### ISSUE THREAD

**Issue by Mitch67** [rudders/homebridge-http#8]
Would it be possible to create other accesory types (currently only switch and lightbulb are possible) ? It would help to control doors, ...

**Comment by rudders** [comment]
Wouldn't be hard at all. I'm away on holidays so can't do much at the moment - feel free to fork and submit a PR though.

**Comment by NovaGL** [comment]
It's really easy if you know how, in my repo I have added one for volume. I don't have any controllable thermostats or anything like that but simply changing things such as brightness to hue changes the way the light works. You can also do status polling. The way I did that is by adding a field called switchhandling

**Comment by rudders** [comment]
Update to the new version and thanks to @NovaGL for his PR!
