### ISSUE TITLE
Feature Request: Automatic turn OFF or ON after configurable time

### ISSUE THREAD

**Issue by peros550** [rudders/homebridge-http#81]
Example: 
A user switches ON a lamp, and the plugin makes sure it will turn of after a predefined interval.  

As far as I know, this kind of automation is not possible through home app. 
I thing it would be a good idea to implement such function inside the plugin. If I'm wrong, I do apologize in advance. 
Thanks,

**Comment by psolin** [comment]
It's already a feature in the broadlink rm homepridge plugin, so hope this helps: https://github.com/lprhodes/homebridge-broadlink-rm
